version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app:delegated
      - /app/venv
      - /app/__pycache__
      - /app/.pytest_cache
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    command: flask run --host=0.0.0.0 --debugger
    restart: unless-stopped 